name: streams
version: 0.1.0.0
github: "cdparks/streams"
category: Tutorials
maintainer: "christopher.daniel.parks@gmail.com"
copyright: "2021 Christopher Parks"
description: Please see the README on GitHub at <https://github.com/cdparks/streams#readme>
license: BSD3

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

ghc-options:
  - -ddump-asm
  - -ddump-cmm
  - -ddump-rule-firings
  - -ddump-rule-rewrites
  - -ddump-simpl
  - -ddump-simpl-iterations
  - -ddump-simpl-stats
  - -ddump-stg
  - -ddump-to-file
  - -dsuppress-coercions
  - -dsuppress-idinfo
  - -dsuppress-module-prefixes
  - -dsuppress-ticks
  - -dsuppress-timestamps
  - -dsuppress-type-applications
  - -dsuppress-uniques

library:
  source-dirs: src

executables:
  streams:
    main: Main.hs
    source-dirs: executables
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - streams
